
package stub;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "univUtilImplService", targetNamespace = "http://ws.lexmark.com/", wsdlLocation = "http://localhost/un?wsdl")
public class UnivUtilImplService
    extends Service
{

    private final static URL UNIVUTILIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException UNIVUTILIMPLSERVICE_EXCEPTION;
    private final static QName UNIVUTILIMPLSERVICE_QNAME = new QName("http://ws.lexmark.com/", "univUtilImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost/un?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UNIVUTILIMPLSERVICE_WSDL_LOCATION = url;
        UNIVUTILIMPLSERVICE_EXCEPTION = e;
    }

    public UnivUtilImplService() {
        super(__getWsdlLocation(), UNIVUTILIMPLSERVICE_QNAME);
    }

    public UnivUtilImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), UNIVUTILIMPLSERVICE_QNAME, features);
    }

    public UnivUtilImplService(URL wsdlLocation) {
        super(wsdlLocation, UNIVUTILIMPLSERVICE_QNAME);
    }

    public UnivUtilImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, UNIVUTILIMPLSERVICE_QNAME, features);
    }

    public UnivUtilImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UnivUtilImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns UnivUtil
     */
    @WebEndpoint(name = "univUtilImplPort")
    public UnivUtil getUnivUtilImplPort() {
        return super.getPort(new QName("http://ws.lexmark.com/", "univUtilImplPort"), UnivUtil.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UnivUtil
     */
    @WebEndpoint(name = "univUtilImplPort")
    public UnivUtil getUnivUtilImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.lexmark.com/", "univUtilImplPort"), UnivUtil.class, features);
    }

    private static URL __getWsdlLocation() {
        if (UNIVUTILIMPLSERVICE_EXCEPTION!= null) {
            throw UNIVUTILIMPLSERVICE_EXCEPTION;
        }
        return UNIVUTILIMPLSERVICE_WSDL_LOCATION;
    }

}
