
package stub;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "univUtil", targetNamespace = "http://ws.lexmark.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface UnivUtil {


    /**
     * 
     * @return
     *     returns stub.Student
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getStudentInfo", targetNamespace = "http://ws.lexmark.com/", className = "stub.GetStudentInfo")
    @ResponseWrapper(localName = "getStudentInfoResponse", targetNamespace = "http://ws.lexmark.com/", className = "stub.GetStudentInfoResponse")
    @Action(input = "http://ws.lexmark.com/univUtil/getStudentInfoRequest", output = "http://ws.lexmark.com/univUtil/getStudentInfoResponse")
    public Student getStudentInfo();

    /**
     * 
     * @param arg2
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "setStudentInfo", targetNamespace = "http://ws.lexmark.com/", className = "stub.SetStudentInfo")
    @ResponseWrapper(localName = "setStudentInfoResponse", targetNamespace = "http://ws.lexmark.com/", className = "stub.SetStudentInfoResponse")
    @Action(input = "http://ws.lexmark.com/univUtil/setStudentInfoRequest", output = "http://ws.lexmark.com/univUtil/setStudentInfoResponse")
    public void setStudentInfo(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        int arg2);

}
